export const taskList = [
    {
        id: 1,
        title: "Tarea 1",
        datetime: "24/01/2022 16:40hs",
        creator: "Juan Perez",
        description: "Lorem ipsum dolor sit amet consectetur adipiscing, elit magnis himenaeos convallis nibh in primis, metus blandit erat ligula felis. Interdum ullamcorper sapien ultricies magnis dui mollis, vitae posuere consequat dignissim tristique rhoncus porta, elementum conubia et duis felis dictumst, sed quisque sollicitudin nunc platea. Metus nibh leo lectus senectus magnis penatibus platea velit litora rhoncus, aliquam ultrices egestas sociosqu mollis hendrerit eleifend tempus feugiat facilisi euismod, id fringilla bibendum praesent nunc laoreet aptent viverra commodo",
        status: "new",
        priority: "high", 
    },
    {
        id: 2,
        title: "Tarea 2",
        datetime: "20/01/2022 16:00hs",
        creator: "Mónica Gonzalez",
        description: "Lorem ipsum dolor sit amet consectetur adipiscing, elit magnis himenaeos convallis nibh in primis, metus blandit erat ligula felis. Interdum ullamcorper sapien ultricies magnis dui mollis, vitae posuere consequat dignissim tristique rhoncus porta",
        status: "in progress",
        priority: "low", 
    },
    {
        id: 3,
        title: "Tarea 3",
        datetime: "12/03/2022 20:00hs",
        creator: "Eduardo Sanchez",
        description: "Lorem ipsum dolor sit amet consectetur adipiscing, elit magnis himenaeos convallis nibh in primis, metus blandit erat ligula felis",
        status: "in progress",
        priority: "high", 
    },
    {
        id: 4,
        title: "Tarea 4",
        datetime: "24/02/2022 16:40hs",
        creator: "Romina Balcarce",
        description: "Lorem ipsum dolor sit amet consectetur adipiscing, elit magnis himenaeos convallis nibh in primis, metus blandit erat ligula felis. Interdum ullamcorper sapien ultricies magnis dui mollis, vitae posuere consequat dignissim tristique rhoncus porta, elementum conubia et duis felis dictumst, sed quisque sollicitudin nunc platea. Metus nibh leo lectus senectus magnis penatibus platea velit litora rhoncus, aliquam ultrices egestas sociosqu mollis hendrerit eleifend tempus feugiat facilisi euismod",
        status: "new",
        priority: "low", 
    },
    {
        id: 5,
        title: "Tarea 5",
        datetime: "19/01/2022 14:30hs",
        creator: "Juan Perez",
        description: "Lorem ipsum dolor sit amet consectetur adipiscing, elit magnis himenaeos convallis nibh in primis, metus blandit erat ligula felis. Interdum ullamcorper sapien ultricies magnis dui mollis, vitae posuere consequat dignissim tristique rhoncus porta, elementum conubia et duis felis dictumst, sed quisque sollicitudin nunc platea",
        status: "finished",
        priority: "high", 
    },
    {
        id: 6,
        title: "Tarea 6",
        datetime: "12/03/2022 16:40hs",
        creator: "Sonia Diaz",
        description: "Lorem ipsum dolor sit amet consectetur adipiscing, elit magnis himenaeos convallis nibh in primis",
        status: "finished",
        priority: "low", 
    }
];